# nginx proxy address - http://172.17.0.1:64580
# shortner - development

name: shortner-dev

x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  shortner:
    image: ghcr.io/apimgr/shortner:devel
    container_name: shortner-app
    hostname: shortner
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      PORT: 80
      DEBUG: true
      MODE: development
      TZ: America/New_York
    volumes:
      - './volumes/config:/config:z'
      - './volumes/data:/data:z'
    ports:
      # Development: accessible from all interfaces, no 172.17.0.1 bind
      - '64580:80'
    healthcheck:
      test: ['CMD', '/usr/local/bin/shortner', '--status']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - shortner-dev

networks:
  shortner-dev:
    name: shortner-dev
    external: false
