// Package security implements the cryptographic and identity primitives
// required by AI.md PART 11 "Security & Logging": the resource-owner /
// operator token model, constant-time comparisons, project-level secret
// generation, click-analytics IP anonymization, and short-code/slug
// validation (IDEA.md "Business rules").
package security

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"fmt"
	"strings"
)

// tokenAlphabet is the URL-safe base62 alphabet used for generated tokens,
// matching the pattern used by config.EnsureToken for the operator token.
// See AI.md PART 11 "API Token Model": "tok_ prefix + 32 URL-safe random
// base62 chars".
const tokenAlphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// TokenLength is the number of random alphabet characters after the
// "tok_" prefix.
const TokenLength = 32

// GenerateToken returns a new "tok_" + 32 URL-safe base62 char token, per
// AI.md PART 11 "API Token Model". Used for resource owner tokens (e.g. a
// link's owner_token); the operator token is generated by
// config.EnsureToken using the same alphabet.
func GenerateToken() (string, error) {
	buf := make([]byte, TokenLength)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("security: generate token: %w", err)
	}
	var b strings.Builder
	b.WriteString("tok_")
	for _, v := range buf {
		b.WriteByte(tokenAlphabet[int(v)%len(tokenAlphabet)])
	}
	return b.String(), nil
}

// HashToken returns the lowercase hex SHA-256 digest of raw, the form
// persisted to the api_tokens table per AI.md PART 11 "API Token Model":
// "The server stores only the SHA-256 hash; the raw token is shown once
// ... and never retrievable again."
func HashToken(raw string) string {
	sum := sha256.Sum256([]byte(raw))
	return hex.EncodeToString(sum[:])
}

// TokenPrefix returns the first 12 characters of raw, used for log
// identification and DB lookup per AI.md PART 11 "API Tokens" schema
// (token_prefix column).
func TokenPrefix(raw string) string {
	if len(raw) <= 12 {
		return raw
	}
	return raw[:12]
}

// CompareTokenHash reports whether raw hashes to storedHash, using a
// constant-time comparison per AI.md PART 11 "Authentication & Identity
// Rules": "Use crypto/subtle.ConstantTimeCompare for ALL token ...
// comparisons. Never compare with ==, bytes.Equal, or strings.EqualFold."
func CompareTokenHash(raw, storedHash string) bool {
	got := HashToken(raw)
	// ConstantTimeCompare requires equal-length slices; hex-encoded
	// SHA-256 digests are always 64 bytes, but guard defensively so a
	// malformed stored hash never short-circuits into a fast/slow path
	// that leaks length via timing.
	if len(got) != len(storedHash) {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(got), []byte(storedHash)) == 1
}

// CompareServerToken reports whether raw matches the operator token
// (server.token), by SHA-256-hashing both sides and comparing in constant
// time. Per AI.md PART 11: "Validated by SHA-256-hashing the inbound
// token and comparing against SHA-256(server.token) with
// subtle.ConstantTimeCompare."
func CompareServerToken(raw, serverToken string) bool {
	if serverToken == "" {
		return false
	}
	return CompareTokenHash(raw, HashToken(serverToken))
}

// GenerateSecret returns n cryptographically random bytes, for use as a
// project-level secret (installation_secret, cookie_signing_key,
// csrf_token_secret — AI.md PART 11 "Cryptographic Keys").
func GenerateSecret(n int) ([]byte, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return nil, fmt.Errorf("security: generate secret: %w", err)
	}
	return buf, nil
}
